##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES
#
# url is your gh-pages base, following the pattern: username.github.io
url: forreymr.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /mjvinyl
# location of code, the full url to your github repository
source-code: https://github.com/forreymr/mjviny

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Meredith & Jeff's Vinyl Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A selection of our albums on vinyl.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: This site is a way for me, Meredith, to practice skills useful to digital librarianship such as web design and creating metadata.
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: forreymr

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: album_metadata

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
